name: tmshub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.2
  animated_splash_screen: ^1.2.0
  flutter_bloc: ^7.2.1
  auto_size_text: 
  flutter_map: ^5.0.0 
  flutter_map_marker_cluster: 
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  dio: 
  dotted_border:
  latlong2: ^0.9.0
  location: ^5.0.3
  http: ^1.1.0
  provider: 
  permission_handler: ^11.0.1
  intl: ^0.18.1
  image_picker: 
  shared_preferences: ^2.2.2
  loader_overlay: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
